let challenge = '   30 Days Of JavaScript    ';
let pattern = /a/gi;
let concat2challenge = '30 Days of';
let concat2challengeBis = 'JavaScript.';
let companies = 'Facebook, Google, Microsoft, Apple, IBM, Oracle, Amazon';
let because = 'You cannot end a sentence with because because because is a conjunction';

console.log("PRINT THE STRING : " + challenge);
console.log("PRINT THE LENGTH : " + challenge.length);
console.log("UPPER CASE : " + challenge.toUpperCase());
console.log("TO LOWER CASE : " + challenge.toLowerCase());
console.log("CUT THE FIRST WORD : " + challenge.substr(2));
console.log("SLICE OUT : " + challenge.slice(0));
console.log("INCLUDES Script? : " + challenge.includes("Script"));
console.log("SPLIT INTO AN ARRAY : ", challenge.split(' '));
console.log("SPLIT INTO AN ARRAY CHAPTER II : ", companies.split(','));
console.log("LE REPLACE DE JAVASCRIPT EN PYTHON : " + challenge.replace("JavaScript", "Python"));
console.log("LE CHARAT : " + challenge.charAt(15));
console.log("INDEX OF : " + challenge.indexOf("a"));
console.log("LAST INDEX OF : " + challenge.lastIndexOf("a"));
console.log("INDEX OF DE BECAUSE  (on va le croire hein) : " + because.indexOf("because"));
console.log("LAST INDEX DE BECAUSE  (on va le croire hein) : " + because.lastIndexOf("because"));
console.log("SEARCH FIRST OCCURENCE OF BECAUSE : " + because.search("because"));
console.log("TRIM (euh bah il veut pas mettre d'espaces donc bon) : " + challenge.trim());
console.log("STARTS WITH : " + challenge.startsWith('3'));
console.log("ENDS WITH : " + challenge.trim().endsWith("t"));
console.log("TON MATCH : " + challenge.match(pattern));
console.log("CONCAT : " + concat2challenge.concat(" " + concat2challengeBis));
console.log("REPEAT : " + challenge.repeat(2));